server:
  port: 8080
  servlet:
    context-path: /account

spring:
  application:
    name: account
  datasource:
    dataSourceClassName: org.postgresql.Driver
    url: jdbc:postgresql://database/inventory
    username: aeto
    password: aeto
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

zuul:
  routes:
    inventory:
      url: http://localhost:8090
    account:
      url: http://localhost:8080
ribbon:
  eureka:
    enabled: false