server:
  port: 8080
  servlet:
    context-path: /account

spring:
  datasource:
    dataSourceClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: aeto
    password: aeto
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration